package com.abilify.springbootrestapi.application.homeservices;

public class ServiceCatalogController {

    /*
     SERVICE CATALOGING DOMAIN:

     1) GET THE LIST OF SERVICES
     2) GET A SERVICE FROM THE LIST
     3) PUT NEW SERVICE ON THE LIST
     4) UPDATE A SERVICE ON THE LIST
     5) DELETE A SERVICE FROM THE LIST

     6) GET THE LIST OF SUB-SERVICES OF A SERVICE
     7) GET A SUB-SERVICE OF A SERVICE FROM THE LIST
     8) PUT NEW SUB-SERVICE OF A SERVICE ON THE LIST
     9) UPDATE A SUB-SERVICE OF A SERVICE ON THE LIST
     10) DELETE A SUB-SERVICE OF A SERVICE FROM THE LIST

     11) GET THE LIST OF SERVICE/SUB-SERVICE SPECIFICATIONS
     12) GET THE SERVICE SPECIFICATION STEPS/INFO OF A SERVICE/SUB-SERVICE
     13) PUT NEW SERVICE SPECIFICATION OF A SERVICE/SUB-SERVICE
     14) UPDATE A SERVICE/SUB-SERVICE SPECIFICATION ON THE LIST
     15) DELETE A SERVICE/SUB-SERVICE SPECIFICATION FROM THE LIST
    */

}
