package com.abilify.springbootrestapi.application.homeservices;

import org.springframework.web.bind.annotation.RestController;

@RestController

public class ServiceOrderingController {

    /*
     SERVICE ORDERING DOMAIN:

     1) GET THE LIST OF SERVICES ORDERS
     2) GET A SERVICE ORDER FROM THE LIST
     3) PUT NEW SERVICE ORDER ON THE LIST
     4) UPDATE A SERVICE ORDER ON THE LIST
     5) DELETE A SERVICE ORDER FROM THE LIST

     6) GET THE LIST OF SUB-SERVICES OF A SERVICE
     7) GET A SUB-SERVICE OF A SERVICE FROM THE LIST
     8) PUT NEW SUB-SERVICE OF A SERVICE ON THE LIST
     9) UPDATE A SUB-SERVICE OF A SERVICE ON THE LIST
     10) DELETE A SUB-SERVICE OF A SERVICE FROM THE LIST

     11) GET THE LIST OF SERVICE/SUB-SERVICE SPECIFICATIONS
     12) GET THE SERVICE SPECIFICATION STEPS/INFO OF A SERVICE/SUB-SERVICE
     13) PUT NEW SERVICE SPECIFICATION OF A SERVICE/SUB-SERVICE
     14) UPDATE A SERVICE/SUB-SERVICE SPECIFICATION ON THE LIST
     15) DELETE A SERVICE/SUB-SERVICE SPECIFICATION FROM THE LIST
    */


}
